// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmkicchndpicswrsvhps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indta2ljY2huZHBpY3N3cnN2aHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDk1ODEsImV4cCI6MjA2NzgyNTU4MX0.KdtVmgbr9dQb-kbo64kJIBnUygKK6pvGw0eVFzB2OyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});